name: flutter_circular_chart
description: Animated radial and pie charts for Flutter
version: 0.0.1
author: Victor Choueiri 
homepage: https://github.com/xqwzts/flutter_circular_chart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0
